[package]
name = "os"
version = "0.1.0"
authors = ["Ana Gelez <ana@gelez.xyz>"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"
lazy_static = { version = "1.0", features = [ "spin_no_std" ] }
spin = "0.5.2"
volatile = "0.2.6"
uart_16550 = "0.2.5"
x86_64 = "0.10.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", # Make it easy to exit QEMU when all tests finished
    "-serial", "stdio", # Redirect serial port output to STDOUT (for easier debugging/testing)
    "-display", "none" # Hide the window when running tests
]
test-success-exit-code = 33
test-timeout = 300
