# Use a different linker for faster compilation

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[alias]
kbuild = "build --target x86_64-os.json -Z build-std=core,alloc -Z build-std-features=compiler-builtins-mem"
boot = "run --package boot-en-train"

